### ISSUE TITLE
list SNPs and their proteins that do not have pathways yet (WikiPathways + Reactome)

### ISSUE THREAD

**Issue by egonw** [wikipathways/sr24-subdomain#10]
Got a from Marek (UMC) a list of diseases and genes, in the supp info, from this article: https://onlinelibrary.wiley.com/doi/10.1002/jimd.12348

**Comment by egonw** [comment]
I have converted the spreadsheet into RDF Turtle now.

**Comment by mjnoga** [comment]
I'm glad you found the table useful!

**Comment by egonw** [comment]
> I'm glad you found the table useful!

We did not quite get to the SNPs, but just having the list of genes indeed was very useful!
