### ISSUE TITLE
discuss allowed interaction data sources

### ISSUE THREAD

**Issue by egonw** [wikipathways/sr24-subdomain#13]
See https://www.wikipathways.org/sr24-curation/reports/WP5176.html#cff6555b

@DeniseSl22, is Reactome okay or not as `Interaction` xref data sources?

**Comment by DeniseSl22** [comment]
Yes, Reactome can also be added, it is also part of the interaction mapping files!

**Comment by egonw** [comment]
Should be fixed by this patch: https://github.com/wikipathways/WikiPathwaysCurator/commit/ae81ec6ce38c16c2280e1364cb49db9e8cd805b0
