### ISSUE TITLE
Complete content needed for the registration

### ISSUE THREAD

**Issue by egonw** [wikipathways/sr24-subdomain#2]
The form to start an action is online [here](https://www.npo3fm.nl/kominactie/start-een-actie), and these are the fields:

**Actietitel**: WikiPathways in actie voor MetaKids

**URL**: https://sr24.wikipathways.org/

**Startdatum**: 1 November

**Omschrijving**:

Onderzoek naar metabole ziekten begint vaak met een overzicht maken van wat er bekent is over de
biologische processes achter de ziekte. WikiPathways is een kennisbron die kaarten maakt van zulke
biologische processen.

Het WikiPathways team van de Universiteit van Maastricht en Maastricht UMC+ komt daarom in actie
om haar kaarten bij te werken voor recente nieuwe inzichten, het toevoegen van ontbrekende kaarten,
en deze kaarten nog beter te maken voor onderzoek.

Deelnemers:
* Egon Willighagen: "Ik ga in de week van 16-20 December voor elke gesponserde euro een minuut werken aan nieuwe en betere beschrijvingen van biologische processen achter metabole ziekten in WikiPathways"

**Bedankt bericht**:

Met uw financiële steun aan deze "open wetenschap" actie, maken wij WikiPathways nog beter in het
ondersteunen van onderzoek naar stofwisselingsziektes en daarmee het werk van de stichting MetaKids.

**Comment by egonw** [comment]
My personal "streefbedrage" is 2400 euro, which is 40 hours * 60 minutes * 1 euro. But we have to list an overall sum

**Comment by LauraSteinbusch** [comment]
Een iets aangepaste tekst:

---

### Omschrijving:

Onderzoek naar metabole ziekten begint vaak met het in kaart brengen van de biologische processen die aan deze ziekten ten grondslag liggen. WikiPathways is een belangrijke bron van kennis, waarbij visuele kaarten worden gemaakt van deze biologische processen.

Het WikiPathways-team van de Universiteit Maastricht en Maastricht UMC+ is daarom aan de slag gegaan om bestaande kaarten te actualiseren met de meest recente inzichten, ontbrekende kaarten toe te voegen, en de kwaliteit van deze kaarten verder te verbeteren voor onderzoek.

### Deelnemers:

Egon Willighagen: "Tijdens de week van 16-20 december zal ik voor elke gesponsorde euro een minuut besteden aan het verbeteren en uitbreiden van beschrijvingen van biologische processen die betrokken zijn bij metabole ziekten in WikiPathways."

### Bedankt:

Dankzij uw financiële steun aan deze 'open wetenschap'-actie kunnen wij WikiPathways verder verbeteren als onderzoeksinstrument voor stofwisselingsziekten en zo het werk van Stichting MetaKids ondersteunen.

**Comment by LauraSteinbusch** [comment]
Deelnemers:
Egon Willighagen: "Tijdens de week van 16-20 december zal ik voor elke gesponsorde euro een minuut besteden aan het verbeteren en uitbreiden van beschrijvingen van biologische processen die betrokken zijn bij metabole ziekten in WikiPathways."
Laura Steinbusch: "Tijdens de week van 16-20 december zal ik voor elke gesponsorde euro een minuut besteden aan het verzamelen van literatuur welke als basis dienen voor verbeteren en uitbreiden van beschrijvingen van biologische processen die betrokken zijn bij metabole ziekten in WikiPathways. Op vrijdag 20 december fiets ik met het metabole team van het MUMC+ naar het glazen huis om het gedoneerde geld over te dragen aan Serious Request."
