### ISSUE TITLE
Set goals and define participant list

### ISSUE THREAD

**Issue by egonw** [wikipathways/sr24-subdomain#3]
Possible "commitments":

- be member of the scientific board, and e.g. do preperatory work:
  - collecting literature that should be cited
  - collect pathway drawings that can be digitized in WikiPathways
- draw/curate pathways in WikiPathways, e.g.
  - ensure all genes and proteins have identifiers
  - proper metabolite identifiers (and ensure they are all in Wikidata)
  - add literature references to all interactions
- annotate pathways with there corresponding metabolic disease
- develop a info or score board to show statistics on the quality of community pathways, e.g.
  - number of data nodes without proper identifiers (should be zero)
  - number of unique literature references
- work with MetaKids/UMD researchers on workflows to use content from the new WikiPathways Community
- ...

**Comment by egonw** [comment]
My commitment: "I will work on 16-20 December in the week of Serious Request 2024 one minute on data curation in WikiPathways for every euro raised in this action" (up to of 40 hours, perhaps).

**Comment by LauraSteinbusch** [comment]
I can help as a scientific advisor in the week of 16-20 december. December 20th I will cycle with the MUMC+ team to Zwolle to hand over the money that we collected.

**Comment by egonw** [comment]
> December 20th I will cycle with the MUMC+ team

yes, I saw that "actie"! Cool! I love cycling, but this is too far for me on my city bike :)
